### PR TITLE
Generalize EstimatorTransformer to multi-output estimators.

### PR DESCRIPTION
**Pull request by CarloLepelaars**
`EstimatorTransformer` will only reshape if either the output shape of a given estimator has length 1 or if the 2nd dimension of the output equals 1. For multi-output estimators the estimator output is returned as is. Solves issue #525

### CODE REVIEW

**Comment by koaning** [comment]
@CarloLepelaars before diving into the code, could you also add a test that confirms the new behavior?

**Comment by CarloLepelaars** [comment]
@koaning 👍 Sure, will do!

**Comment by koaning** [comment]
Any objections against adding a test that uses [MultiOutputRegressor](https://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html#sklearn.multioutput.MultiOutputRegressor)?

**Comment by CarloLepelaars** [comment]
No objections at all! 🙂

**Comment by koaning** [comment]
If only there's a website that clearly explains them ;) 

https://calmcode.io/pytest-tricks/fixtures.html

**Comment by CarloLepelaars** [comment]
Aha, awesome! Will review that Calmcode section! 🙏

**Review by koaning — APPROVED** [review]
Looks good to me!

**Comment by CarloLepelaars** [comment]
Awesome! This is a great project you guys have going! Looking forward to contribute more in the future.

**Pull request merged**
