### PR TITLE
Grouped Transformer Documentation

### PR DESCRIPTION
**Pull request by koaning**
@pim-hoeven this is a section added to the documentation about the transformer. I propose merging this once your PR is done so that the docs are still in sync with what people can download. 

You might like the example I found (also ping @MBrouns). It turns out that you can also use this transformer to scramble gender information. If you group by gender while applying a `StandardScaler` ... suddenly you can't use weight/height anymore to classify male/female. The plot below shows two clusters, these are caused by a species of penguin and the colors of the points represent the sex of the penguins. 

image

### CODE REVIEW

**Comment by pim-hoeven** [comment]
This is really cool!

**Comment by koaning** [comment]
That's certainly fair. Will add.

**Comment by koaning** [comment]
Time to do a new version relase 😃

**Comment by pim-hoeven** [comment]
Nice! Just in time, wanted to use the new `GroupedPredictor` today!

**Comment by koaning** [comment]
@pim-hoeven got a twitter handle? you're getting a shout-out.

**Comment by pim-hoeven** [comment]
No I don't :(. Thanks though!

Op vr 31 jul. 2020 om 11:25 schreef vincent d warmerdam <
notifications@github.com>:

**Pull request merged**
