### PR TITLE
Fixed tests for Grouped Transformer

### PR DESCRIPTION
**Pull request by koaning**
@pim-hoeven this fix might be good enough?

### CODE REVIEW

**Comment by koaning** [comment]
It's for this issue: https://github.com/koaning/scikit-lego/issues/399.

**Comment by pim-hoeven** [comment]
I'll rebase my PR as soon as you merge this.

**Comment by koaning** [comment]
Mhm. There also seems to be something up with the logging.

**Comment by koaning** [comment]
I didn't come up with this one ... this seems to be a `pytest` bug. They just released version 6.0.0 and it seems to have a broken `caplog` fixture. Nothing gets recorded. Will move to an old version of pytest in our build tools I suppose. 

Can confirm locally that the issue does not exist for `pytest==5.4.1`.

**Pull request merged**
