### PR TITLE
Implementation of [FEATURE] hall of fame #296, 

### PR DESCRIPTION
**Pull request by Pverheijen**
Hi there, 

First pull request ever...
I'm not sure if link to the repository is correct, might have to be:

(https://sourcerer.io/fame/koaning/scikit-lego/images/0)](https://sourcerer.io/fame/koaning/scikit-lego/links/0)

instead of:

[](https://sourcerer.io/fame/Pverheijen/koaning/scikit-lego/links/0)

But that did not work locally unfortunately. 

Kind regards,
Peter

### CODE REVIEW

**Comment by koaning** [comment]
1.) I get what this tool tries to do ... and I appreciate you taking the effort ... but I am not 100% sure if this is something I'd like to have on the readme. We already appreciate the people who make a significant contribution in our own special way. We've written signed letters in the past with stickers and we've built a collaborative poem (try it out: `from sklego import this`). 

2.) I fear that this addition might distract the people who just want to learn the tool. 

I'd be more open to have this feature on the documentation page though.

**Comment by koaning** [comment]
Ah. And I now see that there's an issue for this that I added a while ago that I completely forgot about.

**Comment by koaning** [comment]
I'll move this discussion there now.

**Comment by koaning** [comment]
Those markdown links render inside of sphinx?

**Comment by Pverheijen** [comment]
> Those markdown links render inside of sphinx?

I just made the docs locally to check and it's working. 

Contribution hyperlink goes to contribution.html
The contributor links go to the right url as well. 

It seems "/scikit-lego/docs/contribution.html" has slipped through the crack, can you remove this from contributors.rst?

**Comment by Pverheijen** [comment]
I've opened another pull request, this one is incorrect.

**Pull request closed without merging**
