### PR TITLE
Bugfix/p percent divide by zero another try

### PR DESCRIPTION
**Pull request by kayhoogland**

### CODE REVIEW

**Comment by koaning** [comment]
this is *insanely* annoying. 

image

**Comment by MBrouns** [comment]
as a workaround I pushed Kays branch as a branch on our repo (#195) which seems to work. I'll merge when CI is done

**Comment by kayhoogland** [comment]
Thanks! Did you experience this with other PRs as well or could it be caused by my fork?

**Comment by MBrouns** [comment]
PR's on branches of the repo itself work, but on forks they don't. It should be possible with github actions but it doesn't seem to work yet. Does your repo have actions enabled already?

**Comment by kayhoogland** [comment]
I have beta access since of last week but I did not enable it yet.

**Pull request merged**
