### PR TITLE
docs: Make API section nicer

### PR DESCRIPTION
**Pull request by tomasborrella**
issue #326

### CODE REVIEW

**Comment by koaning** [comment]
This is a *huge* improvement. Thanks! @MBrouns I'm cool with these changes, you?

**Comment by MBrouns** [comment]
I'm super happy with these changes! Looks much cleaner

**Comment by koaning** [comment]
@tomasborrella if you ping myself or @MBrouns on twitter/linkedin we will gladly send you a project sticker as a thankyou.

**Comment by tomasborrella** [comment]
> I'm super happy with these changes! Looks much cleaner

I'm really glad to hear that :)

**Comment by tomasborrella** [comment]
> @tomasborrella if you ping myself or @MBrouns on twitter/linkedin we will gladly send you a project sticker as a thankyou.

Cool! I'd ping you both.

**Pull request merged**
