### PR TITLE
Pre commit

### PR DESCRIPTION
**Pull request by koaning**
I've made a start with some of the pre-commit features. There's a bunch of them that are nice ... in particular -> OMG SPELLING!

### CODE REVIEW

**Comment by koaning** [comment]
I'm having a bit of difficulty figuring out how to set codespell to also look in the docs, but I'll figure that out later. Now ... it is time for a morning run!

**Comment by greatsharma** [comment]
https://github.com/koaning/scikit-lego/blob/c410907cbe12b087470d93edb7e25537cf18495c/sklego/common.py#L60

In this change `TrainOnlyMixin.HASHERS` to `TrainOnlyTransformerMixin._HASHERS`

**Comment by greatsharma** [comment]
https://github.com/koaning/scikit-lego/blob/c410907cbe12b087470d93edb7e25537cf18495c/sklego/dummy.py#L25
https://github.com/koaning/scikit-lego/blob/c410907cbe12b087470d93edb7e25537cf18495c/sklego/dummy.py#L45

These should be `(n_samples, n_columns,)`

**Comment by koaning** [comment]
@greatsharma the documents that are affected by the spellcheck are the ones that that changed. i am aiming to first merge your stuff before i merge this one to keep things easy.

**Pull request merged**
