### PR TITLE
[TEST] Compare Travis and Gitpod testing times 

### PR DESCRIPTION
**Pull request by jankeromnes**
Just for testing, please don't merge. And sorry for the noise.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Results:

| Step | Travis 3.6 | Travis 3.7 | Gitpod |
| --- | --- | --- | --- |
| `flake8` | `0m1.669s` | `0m1.473s` | `0m0.686s` |
| `pytest` | `3m5.411s` | `2m57.722s` | `4m29.987s` |
| `doctest` | `0m1.791s` | `0m1.547s` | `0m1.690s` |

Strange, it seems like in the same conditions, Gitpod is indeed slower at running `pytest --disable-warnings --cov=sklego` (on much faster hardware). Maybe there is a way to profile this and find out what makes it slow.

**Comment by koaning** [comment]
This is indeed interesting. Good work!

**Comment by koaning** [comment]
I am seeing something strange happen with a part of the library. 

```
> pytest tests/test_estimators/test_deadzone.py --durations=3
53.91s call     tests/test_estimators/test_deadzone.py::test_deadzone[check_shape_remains_same_regressor]
0.01s call     tests/test_estimators/test_deadzone.py::test_values_uniform[linear]
0.01s call     tests/test_estimators/test_deadzone.py::test_values_uniform[quadratic]
```

**Comment by koaning** [comment]
@jankeromnes This is a hypothesis, but it might be, since I am using loads of numeric libraries, that perhaps the operating system does not come with BLAS instructions?

**Pull request closed without merging**
