### PR TITLE
add notebook explaining the datasets

### PR DESCRIPTION
**Pull request by nvanommeren**
Should solve issue: [DOCS] datasets are currently undocumented #288

### CODE REVIEW

**Comment by koaning** [comment]
I think this looks good as a first start. I'm certainly willing to add this but there are some datasets missing. 

You can check [here](https://scikit-lego.readthedocs.io/en/latest/api/datasets.html) I think this PR is missing; 

- make_simpleseries
- fetch_creditcard
- load_penguins 

I'm certainly willing to merge this work for now. But if you prefer I can also wait until these datasets have also been added.

**Comment by koaning** [comment]
You've placed this notebook in the correct folder by the way. All notebooks related to documentation should go there.

**Comment by nvanommeren** [comment]
How can I forget the penguins ... ;) 

Thanks, added the last three datasets. 

One small remark: the behaviour of `fetch_creditcard` is slightly different compared to the other datasets. When I run it with `as_frame` = True it returns a dictionary including the frame instead of the frame directly.

**Comment by koaning** [comment]
This is true! Well spotted. 

I'm not 100% with how I'd like to handle this forward. Technically all of the `load_*` functions use an API that is inconsistent with the scikit-learn API. The `fetch_*` functions will use a tool inside of scikit-learn which means that it is tricky to not use the official scikit-learn standard. For now I think it is fine if we just clearly document this but in the long run a proper decision has to be made.

I think we're going to move this portion of the library to be 100% consistent with scikit-learn at some point in the future. Don't know when yet though.

**Comment by koaning** [comment]
That said this document looks really great, so I'll go ahead and merge. Thanks! 

If you've got a twitter account I'd love to give you a shoutout and announce this by the way.

**Comment by nvanommeren** [comment]
Yes agree, it would be nicest to be consistent with the scikit-learn library. 

Thanks! I don't have twitter, but added you on LinkdIn.

**Comment by koaning** [comment]
Just gave a small shoutout. Thanks again!

**Comment by koaning** [comment]
Also ... we have stickers! Feel free to ping myself or Matthijs at a meetup in the future.

**Pull request merged**
