### PR TITLE
[wip] add repeating and spanning basis functions

### PR DESCRIPTION
**Pull request by RensDimmendaal**
I'm building preprocessing functions to address:
#20 
#29 

Open Issues:
1. RepeatingBasisFeatures currently accepts only one feature. This is problematic for most tests.

### CODE REVIEW

**Comment by kayhoogland** [comment]
Any updates on this @RensDimmendaal? Would love to use it!

**Comment by RensDimmendaal** [comment]
Far point. I have left this to sit for too long.  It is unclear to me how to run the standard tests this because transformer only accepts one column. @koaning mentioned the idea of wrapping the transformer with a column selector for the tests. I'll try that in the next 7 days.

**Comment by MBrouns** [comment]
Wrapping the thing in a columntransformer is probably a reasonable default anyway! Basically something like this

```
class RepeatingBasisFunction:
    def __init__(column, *args, **kwargs):
        return ColumnTransformer([
            ('repeatingbasis', _RepeatingBasisFunction(*args, **kwargs), column)
        ], remainder='passthrough')

class _RepeatingBasisFunction:
    pass # Your current implementation
```

**Comment by RensDimmendaal** [comment]
Continued in a different branch #171

**Pull request closed without merging**
