### PR TITLE
docs: PCA and UMAP OutlierDetection docstring examples

### LINKED ISSUE #652: `decomposition.pca_reconstruction.PCAOutlierDetection`

### PR DESCRIPTION
**Pull request by anopsy**
# Docs

Added usage examples to:
decomposition.umap_reconstruction.UMAPOutlierDetection
decomposition.pca_reconstruction.PCAOutlierDetection

Fixes #652 and #653 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by anopsy** [comment]
image
Wondering what happend here

**Review by FBruzzesi — COMMENTED** [review]
Just wondering, how did you come up with these array values?
Wouldn't make sense to have some randomly generated arrays (with fixed seed) and then tinker around some value to make them outliers? Point is: currently I cannot spot outliers just by looking at the arrays and everything seems a bit magical.

**On the Github action failing**: Getting a sense that macos-latest runner is on macos 14, and it is breaking most of github actions.
I can't deep dive today, but will try in the coming week.

Anyway, certainly unrelated from the docstring changes

**Comment by anopsy** [comment]
Oh gee, there are even more failed tests now.😮

About examples
I copied the approach with the arrays from scikit-learn docs on PCA (check ss) 
image

and I tinkered around with the values to check how the detectors work for different values in the arrays, n_components and thresholds. I tried to add values that would be clearly an outlier because of the quantiles for example [-100, 99, -99] but the PCA/UMAPOutlierDetectors "classified" them as inliers. I also saw in User Guide  that the values classified by PCA/UMAPOutlierDetectors as outliers, don't look like quantiles based outliers -so you can't  spot them just by looking. If that makes any sense. 

image

**Comment by FBruzzesi** [comment]
Yep the doc page is using iris dataset, which I would not expect to have any particular outlier.
We have one [obvious example](https://github.com/koaning/scikit-lego/blob/main/tests/test_estimators/test_umap_reconstruction.py#L42) in the test suite.

@koaning thoughts on this? In my opinion, it could be worth it to change dataset in the user guide as well. It seems a bit confusing

**Comment by anopsy** [comment]
Sure, I'll do it the way it's done in the test suite.

**Review by FBruzzesi — APPROVED** [review]
Let's ship it ✨

**Pull request merged**
