### PR TITLE
[wip] this is how the repo looks with black.

### PR DESCRIPTION
**Pull request by MBrouns**

### CODE REVIEW

**Comment by koaning** [comment]
not bad, but i daresay we should first merge AllTheThings[tm] because black will cause a merge conflict.

**Comment by MBrouns** [comment]
Agreed. I do think it improved the state overall though so I'm open to doing this!

**Comment by koaning** [comment]
coolio.

**Comment by koaning** [comment]
We might need to expand the "contributing" section as well if we want to add a pre-comit hook.

**Pull request closed without merging**
