### PR TITLE
Capture error message in logfile

### PR DESCRIPTION
**Pull request by Hugovdberg**
When a function that is logged with `sklego.pandas_utils.log_step` raises an error there is no entry in the log. For interactive purposes this might not be a big issue but when running the script automatically it is kind of annoying that the step that failed and the associated error is actually missing from the log. This PR wraps the call to `func` in a `try-except-finally` block to always write the step to the log with a message that it failed (and without trying to parse the result). It also adds a flag to the `log_step` signature whether to capture the actual error message in the log or just the notice that it failed.

### CODE REVIEW

**Comment by MBrouns** [comment]
I really like this addition! it looks good to me, what do you think @koaning ?

**Comment by koaning** [comment]
This is a totally sensible addition. In fact, I'll gladly make a new release just to include this feature 👍

**Review by koaning — APPROVED** [review]

**Comment by koaning** [comment]
New release is out there. 

@Hugovdberg got a twitter? I usually like to give shout-outs to PRs like this.

**Comment by Hugovdberg** [comment]
@koaning I'm Hugovandenberg on Twitter

**Pull request merged**
