### PR TITLE
Adding Verbosity to GMM Classifiers

### PR DESCRIPTION
**Pull request by arose13**
The bayesian classifiers have verbosity the mle version does not.

Perhaps also adding `**gmm_kwargs` would permanently solve this problem.

### CODE REVIEW

**Comment by koaning** [comment]
some of the `**gmm_kwargs` tricks won't fly in scikit-learn's testing framework so I'd prefer to not go that far. adding verbose mode seems perfectly fine tho.

**Comment by MBrouns** [comment]
varargs or varkwargs in the `__init__` are indeed not allowed in `scikit-learn` as the `clone` implementation (used in gridsearch for example) uses function definition inspection of the `__init__` to figure out what parameters need to be copied over to new instances. If you use varargs or varkwargs, you can't name the individual attributes anymore and cloning will probably result in some parameters not being set correctly

**Comment by koaning** [comment]
CI also seems to be failing. Internally it looks as if an `int` accidentally got converted to a `tuple`? 

```
GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,

                means_init=None, n_compone...ne, reg_covar=1e-06, tol=0.001, verbose=(0,),

                verbose_interval=10, warm_start=False, weights_init=None)
```

@arose13 do you also get this result locally?

**Comment by arose13** [comment]
@koaning I didn't get that error but I'm running Python 3.7 so maybe that's why. I'm creating a virtual environment now and rerunning the tests to see if I can get it to break.

PS: @koaning @MBrouns didn't know about that cloning stuff. Interesting I'll say.

**Comment by koaning** [comment]
found the error. note the comma at the end; 

```
self.verbose = verbose,
```

**Comment by koaning** [comment]
The code formatting is complaining now. If you run this locally, what happens? 

```
make develop
make check
make black
```

**Comment by arose13** [comment]
I've only been running the tests 1 by 1. It looks like black has failed but I'll run those and see what's up

**Comment by koaning** [comment]
LGTM.

@arose13 thanks for the PR! 

One thing worth mentioning; we just did a release last week so it might take a bit before this is on pypi. If this is a change you need sooner rather than later know that you can pip install via git too.

**Comment by arose13** [comment]
@koaning understood and thanks for the merge

**Pull request merged**
