### PR TITLE
fix tests sklearn one

### PR DESCRIPTION
**Pull request by koaning**
@MBrouns I think these are the tests that are the culprits for scikit-learn v1.

We can merge this and specify sklearn>=1.0.0 once it's officially released. Sound good?

### CODE REVIEW

**Comment by MBrouns** [comment]
There's no need to enforce `sklearn>=1` for end-users though right?

**Comment by koaning** [comment]
That's true. No real need to upgrade to another version of scikit-learn as long as we keep cron-testing for a modern version. 

I do feel like it makes sense to keep the stack modern though. We shouldn't immediately upgrade our stuff, but it'll be a burden for us to maintain many old versions of pandas/scikit-learn.

**Comment by MBrouns** [comment]
Yea that's fair, but sklearn 0.24 is still quite recent

**Comment by koaning** [comment]
True. 

Can I merge this though?

**Comment by MBrouns** [comment]
Ah yes, of course!

**Review by MBrouns — APPROVED** [review]

**Pull request merged**
