### PR TITLE
Add the Hearts dataset

### PR DESCRIPTION
**Pull request by kayhoogland**
Hey 👋 

I heard you guys on De Dataloog and it triggered me to pick up an issue. In this PR I added the hearts dataset as described in https://github.com/koaning/scikit-lego/issues/289. I decided to limit the dataset to the one of Cleveland containing 13 features and 1 label since it is the most / only used dataset. 

Let me know what you think!

### CODE REVIEW

**Comment by koaning** [comment]
@kayhoogland thanks!

Mhm ... I see some parts failing in the tests. It strikes me as strange considering these parts have little to do with the written code. But there was a scikit-learn release [recently](https://pypi.org/project/scikit-learn/0.23.0/) that might be related. 

@MBrouns figured I'd give you a ping.

**Comment by koaning** [comment]
Yeah I can confirm that the master branch is breaking locally too so this issue is unrelated to this PR. Haven't figured out what exactly is breaking here. It may be a test that's been added or it may be a change in their implementation of linear models. Not super sure.

**Comment by koaning** [comment]
@kayhoogland this looks green to me but I prefer to fix the other bug first to keep master green. then we'll merge this PR and do a release.

**Comment by MBrouns** [comment]
pull request for the other issue is open at #347. Once that's green we can rebase this and merge!

**Pull request merged**
